[package]
name = "day1"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"

[profile.dev]
opt-level = 0
debug = true
strip = "none"
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
